// index.tsx
'use client'

import type { JSX } from 'react'

import { AdCard, NucMenuTree, NucSettingsCardContent, useRoute } from 'nucleify'

import './_index.scss'

export function NucSettingsPage(): JSX.Element {
  const route = useRoute()
  const cardId = route.hash.replace('#', '') || 'settings'

  return (
    <div className="panel-container">
      <AdCard className="settings-main-card" id={cardId}>
        <NucMenuTree />
        <div className="settings-main-card-content">
          <NucSettingsCardContent />
        </div>
      </AdCard>
    </div>
  )
}

// index.vue
<template>
  <div class="panel-container">
    <ad-card class="settings-main-card" :id="route.hash.replace('#', '')">
      <template #content>
        <nuc-menu-tree />
        <div class="settings-main-card-content">
          <nuc-settings-card-content />
        </div>
      </template>
    </ad-card>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from 'nuxt/app'

const route = useRoute()
</script>

<style lang="scss">
@import 'index';
</style>
