// components/card/index.vue
<template>
  <ad-card class="settings-card settings-small-card">
    <template #header>
      <div class="settings-card-header-container">
        <ad-heading :tag="4" :text="props.heading" />

        <ad-button
          v-if="props.showButton"
          :icon="props.buttonIcon || 'prime:refresh'"
          ad-type="main"
          class="refresh-button"
          rounded
          text
          @click="props.onButtonClick && props.onButtonClick()"
        />
      </div>
    </template>

    <template #content> <slot /> </template>
  </ad-card>
</template>

<script setup lang="ts">
import type { NucSettingsCardInterface } from 'nucleify'

const props = defineProps<NucSettingsCardInterface>()
</script>

<style lang="scss">
@import 'index';
</style>

// components/card/index.tsx
'use client'

import type { JSX, ReactNode } from 'react'

import type { NucSettingsCardInterface } from 'nucleify'
import { AdButton, AdCard, AdHeading } from 'nucleify'

import './_index.scss'

export function NucSettingsCard({
  heading,
  showButton,
  buttonIcon = 'prime:refresh',
  onButtonClick,
  children,
}: NucSettingsCardInterface & { children?: ReactNode }): JSX.Element {
  return (
    <AdCard
      className="settings-card settings-small-card"
      header={
        <div className="settings-card-header-container">
          <AdHeading tag={4} text={heading} />
          {showButton ? (
            <AdButton
              icon={buttonIcon}
              adType="main"
              className="refresh-button"
              rounded
              text
              type="button"
              onClick={onButtonClick}
            />
          ) : null}
        </div>
      }
    >
      {children}
    </AdCard>
  )
}
