// components/content/index.tsx
'use client'

import type { JSX } from 'react'

import {
  NucChartSettingsCard,
  NucColorSettingsCard,
  NucDocuments,
  NucModulesSettingsDetail,
  NucSettingsPreferencesTheme,
  NucSettingsStaffModules,
  NucUsersProfileNotificationsAlerts,
  NucUsersProfilePersonalInfo,
  t,
  useRoute,
} from 'nucleify'

const GRIDED_HASHES = [
  '#preferences-theme',
  '#my-profile-personal-info',
  '#my-profile-notifications-alerts',
  '#module-nuc_documents',
] as const

export function NucSettingsCardContent(): JSX.Element {
  const route = useRoute()
  const gridedContent = GRIDED_HASHES.includes(
    route.hash as (typeof GRIDED_HASHES)[number]
  )
  const isModuleDetail = route.hash.includes('#module-') && !gridedContent

  if (gridedContent) {
    return (
      <div className="grided-content">
        {route.hash === '#preferences-theme' ? (
          <NucSettingsPreferencesTheme />
        ) : null}
        {route.hash === '#my-profile-personal-info' ? (
          <NucUsersProfilePersonalInfo />
        ) : null}
        {route.hash === '#my-profile-notifications-alerts' ? (
          <NucUsersProfileNotificationsAlerts />
        ) : null}
        {route.hash === '#module-nuc_documents' ? <NucDocuments /> : null}
      </div>
    )
  }

  if (route.hash === '#modules') {
    return <NucSettingsStaffModules />
  }

  if (isModuleDetail) {
    return (
      <NucModulesSettingsDetail>
        {route.hash === '#module-nuc_colors' ? (
          <NucColorSettingsCard heading={t('settings-colors')} />
        ) : null}
        {route.hash === '#module-nuc_charts' ? (
          <NucChartSettingsCard heading={t('settings-charts')} />
        ) : null}
      </NucModulesSettingsDetail>
    )
  }

  return <></>
}

// components/content/index.vue
<template>
  <div class="grided-content" v-if="gridedContent">
    <nuc-settings-preferences-theme
      v-if="route.hash === '#preferences-theme'"
    />
    <nuc-users-profile-personal-info
      v-if="route.hash === '#my-profile-personal-info'"
    />
    <nuc-users-profile-notifications-alerts
      v-if="route.hash === '#my-profile-notifications-alerts'"
    />
    <nuc-documents v-if="route.hash === '#module-nuc_documents'" />
  </div>
  <nuc-settings-staff-modules v-if="route.hash === '#modules'" />
  <nuc-modules-settings-detail
    v-if="route.hash.includes('#module-') && !gridedContent"
  >
    <nuc-color-settings-card v-if="route.hash === '#module-nuc_colors'" />
    <nuc-chart-settings-card v-if="route.hash === '#module-nuc_charts'" />
  </nuc-modules-settings-detail>
</template>

<script setup lang="ts">
import { useRoute } from 'nuxt/app'
import { computed } from 'vue'

import {
  NucUsersProfileNotificationsAlerts,
  NucUsersProfilePersonalInfo,
  NucSettingsPreferencesTheme,
  NucSettingsStaffModules,
} from 'nucleify'

const route = useRoute()

const gridedHashes = [
  '#preferences-theme',
  '#my-profile-personal-info',
  '#my-profile-notifications-alerts',
  '#module-nuc_documents',
]

const gridedContent = computed(() => {
  return gridedHashes.includes(route.hash)
})
</script>
