// components/content/general/preferences/theme/index.vue
<template>
  <nuc-color-settings-card :heading="t('settings-colors')" />
  <hr class="settings-card-divider" />
  <nuc-chart-settings-card :heading="t('settings-charts')" />
  <hr class="settings-card-divider" />
  <nuc-dock-settings-card :heading="t('settings-dock-style')" />
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { t } = useI18n()
</script>

// components/content/general/preferences/theme/index.tsx
'use client'

import type { JSX } from 'react'

import {
  NucChartSettingsCard,
  NucColorSettingsCard,
  NucDockSettingsCard,
  t,
} from 'nucleify'

export function NucSettingsPreferencesTheme(): JSX.Element {
  return (
    <>
      <NucColorSettingsCard heading={t('settings-colors')} />
      <hr className="settings-card-divider" />
      <NucChartSettingsCard heading={t('settings-charts')} />
      <hr className="settings-card-divider" />
      <NucDockSettingsCard heading={t('settings-dock-style')} />
    </>
  )
}
